#include <string.h>

#include "raygui.h"
#include "raylib.h"

#include "gui/core/gui_action_rules.h"
#include "gui/core/gui_help.h"
#include "gui/frontends/functional/gui_fixed_layout.h"
#include "gui/gui_common.h"

static Rectangle ToRayRect(GuiRect rect) {
  Rectangle out = {rect.x, rect.y, rect.width, rect.height};
  return out;
}

static bool ActionButton(GuiUiState *state, Rectangle bounds, const char *text,
                         GuiActionId action_id, const char *help_message) {
  GuiActionAvailability availability = {0};
  GuiResolveActionAvailability(state, action_id, &availability);
  if (availability.enabled) {
    GuiHelpRegister(bounds, help_message);
  } else {
    char blocked_help[APP_MAX_ERROR + 96] = {0};
    snprintf(blocked_help, sizeof(blocked_help), "%s (blocked: %s)",
             help_message, availability.reason);
    GuiHelpRegister(bounds, blocked_help);
  }
  bool clicked = GuiButtonStyled(bounds, text, availability.enabled, false);
  if (!availability.enabled &&
      CheckCollisionPointRec(GetMousePosition(), bounds) &&
      IsMouseButtonPressed(MOUSE_LEFT_BUTTON) &&
      availability.reason[0] != '\0') {
    strncpy(state->banner_message, availability.reason,
            sizeof(state->banner_message) - 1);
  }
  return availability.enabled && clicked;
}

void GuiDrawOrganizePanel(GuiUiState *state, Rectangle panel_bounds) {
  if (!state) {
    return;
  }

  GuiOrganizePanelLayout layout = {0};
  GuiRect panel = {panel_bounds.x, panel_bounds.y, panel_bounds.width,
                   panel_bounds.height};
  GuiBuildOrganizePanelLayout(panel, &layout);

  GuiLabel(ToRayRect(layout.group_label), "Group-by keys");
  GuiHelpRegister(ToRayRect(layout.group_label),
                  "Comma-separated grouping keys used by organize operations");
  GuiTextBox(ToRayRect(layout.group_input), state->group_by,
             (int)sizeof(state->group_by), true);
  GuiHelpRegister(ToRayRect(layout.group_input),
                  "Allowed: date,camera,format,orientation,resolution");

  if (ActionButton(state, ToRayRect(layout.preview_button), "Preview Organize",
                   GUI_ACTION_ORGANIZE_PREVIEW,
                   "Preview file moves without changing filesystem")) {
    GuiUiStartTask(state, GUI_TASK_PREVIEW_ORGANIZE);
  }
  if (ActionButton(state, ToRayRect(layout.execute_button), "Execute Organize",
                   GUI_ACTION_ORGANIZE_EXECUTE,
                   "Execute organize plan and write rollback manifest")) {
    GuiUiStartTask(state, GUI_TASK_EXECUTE_ORGANIZE);
  }
  if (ActionButton(state, ToRayRect(layout.rollback_button), "Rollback",
                   GUI_ACTION_ROLLBACK,
                   "Restore files from manifest generated by Execute Organize")) {
    GuiUiStartTask(state, GUI_TASK_ROLLBACK);
  }

  GuiHelpDrawHintLabel(
      ToRayRect(layout.info_label),
      "Use group-by keys to preview/execute organize. Rollback requires manifest.");
}
