#ifndef ONNX_PROVIDER_INTERNAL_H
#define ONNX_PROVIDER_INTERNAL_H

#define ML_DEFAULT_CLASSIFICATION_MODEL "clf-default.onnx"
#define ML_DEFAULT_TEXT_MODEL "text-default.onnx"

#endif // ONNX_PROVIDER_INTERNAL_H
